consumer_front/controllers/PropdealController.php
<?php
namespace consumer_front\controllers;

use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\base\InvalidValueException;
use common\components\filters\LanguageFilter;
use common\models\property;
use common\models\account\PaypalService;

class PropdealController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'roles' => ['@']],
                ],
            ],
            'language' => [
                'class' => LanguageFilter::className(),
            ],
        ];
    }
    
    public function actionStocks($prop_id)
    {
        $model = property\Deal::getInst($prop_id, property\Deal::SCENARIO_RESERVE);
        $detail = $model->getStockDetail(Yii::$app->user->id);
        
        if ($model->load(Yii::$app->request->post()) && $model->reserveStock(Yii::$app->user->id)) {
            $flow_token = $model->saveFlowData(Yii::$app->user->id);
            Yii::$app->session->set('buy_stock_flow_token', $flow_token);
            
            // if (Yii::$app->user->identity->point->payment_account) {
                // $action = 'select';
            // } else {
                // $action = 'add';
            // }
            // return $this->redirect(Url::to(['account/'.$action, 'ref' => 'deal']));
            return $this->redirect(Url::to(['confirm', 'act' => 'paypal', 'acid' => Yii::$app->user->id]));
        } else {
            return $this->render('stocks', [
                'model' => $detail,
            ]);
        }
    }
    
    public function actionConfirm()
    {
        $params = [
            'token' => Yii::$app->session->get('buy_stock_flow_token'),
            'account_type' => Yii::$app->request->get('act'),
            'account_id' => Yii::$app->request->get('acid'),
        ];
        $model = property\Deal::virefyFlowData(Yii::$app->user->id, $params);
        
        return $this->render('confirm', [
            'model' => $model,
            'action' => 'confirm',
        ]);
    }
    
    public function actionPayment()
    {
        $post = Yii::$app->request->post();
        $post['Deal']['token'] = Yii::$app->session->get('buy_stock_flow_token');
        $model = property\Deal::virefyFlowData(Yii::$app->user->id, $post['Deal']);
        
        $data = $model->flow_data;
        $data['title'] = $model->prop_info->title . 'の株';
        $data['desc'] = $model->prop_info->title . 'の株の購入';
        $data['return_url'] = Url::toRoute(['buy', 't' => $data['token']], true);
        $data['cancel_url'] = Url::toRoute(['payment', 'failed' => '1'], true);
        
        if (!Yii::$app->request->get('failed')) {
            $return_url = PaypalService::createPayment($data);
            if ($return_url) {
                return $this->redirect($return_url);
            }
        }
        
        return $this->render('confirm', [
            'model' => $model,
            'action' => 'payment',
            'payment_failed' => 'paypal',
        ]);
    }
    
    public function actionBuy()
    {
        $token = Yii::$app->request->get('t');
        if (!$token || $token !== Yii::$app->session->get('buy_stock_flow_token')) {
            throw new InvalidValueException('Invalid flow token data.');
        }
        
        $payment_data = [
            'user_id' => Yii::$app->user->id,
            'paymentId' => Yii::$app->request->get('paymentId'),
            'PayerID' => Yii::$app->request->get('PayerID'),
        ];
        $model = property\Deal::virefyFlowData(Yii::$app->user->id, ['token' => $token]);
        $stocks_model = $model->buy(Yii::$app->user->id, $payment_data);
        return $this->redirect(Url::to(['result']));
    }
    
    public function actionResult()
    {
        $token = Yii::$app->session->get('buy_stock_flow_token');
        $flow_data = Yii::$app->cache->get($token);
        if (!$flow_data || $flow_data['user_id'] != Yii::$app->user->id || !isset($flow_data['complete'])) {
            throw new InvalidValueException('Invalid flow token data.');
        }
        
        $prop_info = property\Info::findOne($flow_data['prop_id']);
        
        // property\Deal::deleteFlowData($token);
        
        return $this->render('result', [
            'flow_data' => $flow_data,
            'prop_info' => $prop_info,
        ]);
    }
    
}

consumer_front/controllers/UserController.php
<?php
namespace consumer_front\controllers;

use Yii;
use yii\base\DynamicModel;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\data\ActiveDataProvider;
use yii\web\Response;
use yii\base\InvalidValueException;
use common\components\filters\LanguageFilter;
use common\models\account;
use common\models\user;
use common\models\property;
use common\models\fee;

class UserController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    ['allow' => true, 'roles' => ['@']],
                ],
            ],
            'language' => [
                'class' => LanguageFilter::className(),
            ],
        ];
    }
    
    public function actionDashboard()
    {
        $user_id = Yii::$app->user->id;
        $point = user\Point::findOne($user_id);
        $stockProps = property\Stocks::getUserPropList($user_id);
        $recommendProp = property\Info::findOneForPanel(7);
        $earnings = new ActiveDataProvider([
            'query' => user\EarningsHistory::getListByUser($user_id, null, ['fromDate' => 'first day of today 6 months ago']),
            'pagination' => false,
        ]);
        
        return $this->render('index', [
            'point' => $point,
            'stockProps' => $stockProps,
            'earnings' => $earnings,
            'recommendProp' => $recommendProp,
        ]);
    }
    
    public function actionPoint()
    {
        $user_id = Yii::$app->user->id;
        $point = user\Point::findOne($user_id);
        $recommendProp = property\Info::findOneForPanel(7);
        
        $point_his = new ActiveDataProvider([
            'query' => user\PointHistory::find()->where(['user_id' => Yii::$app->user->id])->orderBy('created_at DESC'),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        
        return $this->render('point', [
            'point' => $point,
            'point_his' => $point_his,
            'recommendProp' => $recommendProp,
        ]);
    }
    
    public function actionPointExchange()
    {
        $user_id = Yii::$app->user->id;
        $point = user\Point::findOne($user_id);
        
        if ($point->points <= 0) {
            throw new InvalidValueException('Not enough points.');
        }
        
        $paypal = account\Paypal::findOne($user_id);
        if (!$paypal) {
            throw new InvalidValueException('No paypal data.');
        }
        
        $model = new DynamicModel(['amount' => null]);
        $model->addRule(['amount'], 'number', ['max' => floor($point->points)])
              ->addRule(['amount'], 'required');
        
        return $this->render('point-exchange', [
            'point' => $point,
            'model' => $model,
            'paypal' => $paypal,
        ]);
    }
    
    public function actionPointExchangeConfirm()
    {
        $user_id = Yii::$app->user->id;
        $point = user\Point::findOne($user_id);
        
        $paypal = account\Paypal::findOne($user_id);
        if (!$paypal) {
            throw new InvalidValueException('No paypal data.');
        }
        
        $model = new DynamicModel(['amount' => null, 'fee' => null]);
        $model->addRule(['amount'], 'number', ['max' => floor($point->points)])
              ->addRule(['amount'], 'required');
        
        if (!$model->load(Yii::$app->request->post()) || $point->points < $model->amount) {
            throw new InvalidValueException('Invalid flow token data.');
        }
        
        if (Yii::$app->request->post('exchange')) {
            try {
                account\PaypalService::payout([
                    'amount' => $model->amount,
                    'email' => $paypal->email,
                    'email_subject' => Yii::t('app', 'ポイント換金処理のお知らせ'),
                ]);
                user\Point::outgo($user_id, $model->amount, user\PointHistory::ACT_EXCHANGE_POINTS);
            } catch (Exception $e) {
                throw new InvalidValueException('Paypal payout request faild.');
            }
            
            $this->redirect('point-exchange-result');
        }
        
        return $this->render('point-exchange-confirm', [
            'point' => $point,
            'model' => $model,
            'paypal' => $paypal,
        ]);
    }
    
    public function actionPointExchangeResult()
    {
        return $this->render('point-exchange-result');
    }
    
    public function actionAccount()
    {
        return $this->render('account');
    }
    
    public function actionPropprofit()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        
        $prop_id = Yii::$app->request->post('prop_id');
        if (!$prop_id) {
            return ['error' => 'no prop_id'];
        }
        
        $profits = new ActiveDataProvider([
            'query' => user\EarningsHistory::getListByUser(Yii::$app->user->id, $prop_id),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
        
        $detail_html = $this->renderPartial('_prop_profit_detail', ['profits' => $profits]);
        return ['html' => $detail_html];
    }
}

consumer_front/views/propdeal/confirm.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = $model->prop_info->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prop-stocks">
    <h1 class="h2 title"><?= Html::encode($this->title) ?></h1>
    <div class="body-content container">
        
        <div class="flow-step-indicator">
            <ul id="progress" class="progress-4">
                <li><?= Yii::t('app', '購入株の選択')?></li>
                <li <?php if($action == 'confirm'):?>class="active"<?php endif?>><?= Yii::t('app', '購入情報確認')?></li>
                <li <?php if($action == 'payment'):?>class="active"<?php endif?>><?= Yii::t('app', '支払い認証')?></li>
                <li><?= Yii::t('app', '完了')?></li>
            </ul>
            <div style="clear: both;text-align:center;"></div>
        </div>
        
        
        <div class="row">
            <div class="col-md-8 prop-stock-confirm-body">
                
                <div class="buy-stock-confirm">
                <?php if (isset($payment_failed)):?>
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Error!</strong> <?= Yii::t('app', 'PayPalの支払い処理に失敗しました。お手数ですが再度試してください。')?>
                    </div>
                <?php endif?>
                    
                    <table class="table">
                        <caption><?= Yii::t('app', '購入詳細情報')?></caption>
                        <tbody>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '物件名')?></th>
                                <td><?= Html::encode($model->prop_info->title)?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '購入株数')?></th>
                                <td><?= $model->flow_data['required_num']?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '購入株内訳')?></th>
                                <td class="buy-stocks-detail">
                                    <table class="table table-condensed"><tbody>
                                        <tr>
                                            <th scope="row"><?= Yii::t('app', '株数')?></th>
                                            <th scope="row"><?= Yii::t('app', '株単価')?></th>
                                        </tr>
                                    <?php foreach($model->flow_data['required_stock_list'] as $stock_data):?>
                                        <tr>
                                            <td><?= $stock_data['num']?></td>
                                            <td><?= Yii::$app->formatter->asCurrency($stock_data['unit_price'])?></td>
                                        </tr>
                                    <?php endforeach?>
                                    </tbody></table>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '購入株総額')?></th>
                                <td><?= Yii::$app->formatter->asCurrency($model->flow_data['required_price'])?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '手数料')?></th>
                                <td><?= Yii::$app->formatter->asCurrency($model->flow_data['fee'])?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '消費税')?></th>
                                <td><?= Yii::$app->formatter->asCurrency($model->flow_data['tax'])?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '適用キャンペーン')?></th>
                                <td>
                            <?php foreach($model->prop_info->campaigns as $campaign):?>
                                    <span class="campaign-label campaign-label-<?= $campaign->class?>"><?= $campaign->label?></span>
                            <?php endforeach?>
                                </td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '支払総額')?></th>
                                <td><?= Yii::$app->formatter->asCurrency($model->flow_data['charge'])?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '支払方法')?></th>
                                <td>
                                    <div class="pay-type-paypal success">
                                        <p class="header"><i class="fa fa-paypal"></i> <?= Yii::t('app', 'PayPal')?></p>
                                        <p><?= Yii::t('app', '決済サービスPayPalを利用して支払いを行います。')?></p>
                                        <p><?= Yii::t('app', 'これから購入した株で得た収入もPayPalアカウントを通して支払われますので、PayPalアカウントを所持していない場合はアカウントを作成して決済を行ってください。')?></p>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <div class="buy-stock-confirm-btn">
                        <?php $form = ActiveForm::begin(['action' => 'payment']); ?>
                            <?= Html::activeHiddenInput($model, 'prop_id')?>
                            <?php true//Html::activeHiddenInput($model, 'account_type', ['value' => $account_type])?>
                            <?php true//Html::activeHiddenInput($model, 'account_id', ['value' => $account_id])?>
                            <div class="form-group">
                                <?= Html::submitButton('<b><i class="fa fa-paypal"></i> '.Yii::t('app', '支払いに進む').'</b>', ['class' => 'btn btn-success btn-lg']) ?>
                            </div>
                        <?php ActiveForm::end(); ?>
                        
                        <!-- <a href="<?= Url::toRoute(['buy', 't' => $model->flow_data['token']])?>"><?= Html::submitButton('<b>'.Yii::t('app', '支払いに進む (FOR TEST)').'</b>', ['class' => 'btn btn-success btn-lg']) ?></a> -->
                    </div>
                    
                </div>
                
            </div>
            
            <div class="col-md-4 prop-stock-side">
                <div class="warning-panel">
                    <div class="bold">
                        <i class="fa fa-exclamation-triangle"></i> 予定金額完了まで契約は成立しません
                    </div>
                    <p>
                        予定金額100%到達まで売買契約が成立しません
                    </p>
                    <p>
                        ですが、予約金として手続きが完了次第、予約した金額の10%の支払いが発生します。予約キャンセル時は払い戻し致します。最終契約成立時は残りの90%の支払いが発生します。
                    </p>
                </div>
                <div class="help-panel">
                    <h4 class="h6 bold"><?= Yii::t('app', 'よくある質問')?></h4>
                    <ul class="">
                        <li class="collapsed" role="button" data-toggle="collapse" href="#collapse1" aria-expanded="false" aria-controls="collapse1">
                            質問１
                        </li>
                        <div class="collapse" id="collapse1">
                            回答１、文言も長い
                        </div>
                        <li class="collapsed" role="button" data-toggle="collapse" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
                            質問2
                        </li>
                        <div class="collapse" id="collapse2">
                            回答2、文言も長い
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        
    </div>

</div>

consumer_front/views/propdeal/result.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = $prop_info->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="prop-stocks">
    <h1 class="h2 title"><?= Html::encode($this->title) ?></h1>
    <div class="body-content container">
        
        <div class="flow-step-indicator">
            <ul id="progress" class="progress-4">
                <li><?= Yii::t('app', '購入株の選択')?></li>
                <li><?= Yii::t('app', '購入情報確認')?></li>
                <li><?= Yii::t('app', '支払い認証')?></li>
                <li class="active"><?= Yii::t('app', '完了')?></li>
            </ul>
            <div style="clear: both;text-align:center;"></div>
        </div>
        
        
        <div class="row">
            
            <div class="col-md-8 prop-stock-confirm-body">
                
                <div class="buy-stock-confirm">
                    <h2 class="buy-stock-result-title"><?= Yii::t('app', '購入手続完了致しました！')?></h2>
                    
                    <table class="table">
                        <tbody>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '物件名')?></th>
                                <td><?= Html::encode($prop_info->title)?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '購入株数')?></th>
                                <td><?= $flow_data['required_num']?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', '支払総額')?></th>
                                <td><?= Yii::$app->formatter->asCurrency($flow_data['charge'])?></td>
                            </tr>
                            <tr>
                                <th scope="row"><?= Yii::t('app', 'PayPal請求書ID')?></th>
                                <td><?= Html::encode('')?></td>
                            </tr>
                            <tr><td></td><td></td></tr>
                        </tbody>
                    </table>
                    
                    <div class="buy-stock-confirm-btn">
                        <?= Html::a(Yii::t('app', 'ダッシュボード'), '/user/dashboard', ['class' => 'btn btn-success']) ?>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4 prop-stock-side">
                <div class="warning-panel">
                    <div class="bold">
                        <i class="fa fa-exclamation-triangle"></i> 予定金額完了まで契約は成立しません
                    </div>
                    <p>
                        予定金額100%到達まで売買契約が成立しません
                    </p>
                    <p>
                        ですが、予約金として手続きが完了次第、予約した金額の10%の支払いが発生します。予約キャンセル時は払い戻し致します。最終契約成立時は残りの90%の支払いが発生します。
                    </p>
                </div>
                <div class="help-panel">
                    <h4 class="h6 bold"><?= Yii::t('app', 'よくある質問')?></h4>
                    <ul class="">
                        <li class="collapsed" role="button" data-toggle="collapse" href="#collapse1" aria-expanded="false" aria-controls="collapse1">
                            質問１
                        </li>
                        <div class="collapse" id="collapse1">
                            回答１、文言も長い
                        </div>
                        <li class="collapsed" role="button" data-toggle="collapse" href="#collapse2" aria-expanded="false" aria-controls="collapse2">
                            質問2
                        </li>
                        <div class="collapse" id="collapse2">
                            回答2、文言も長い
                        </div>
                    </ul>
                </div>
            </div>
        </div>
        
    </div>

</div>